In [3]:
import torch
import numpy as np

In [4]:
# 1. torch.cat()
# Функция конкатенации объединяет тензоры вдоль заданной размерности. 
# Размеры должны совпадать.
#
# dim=0 означает объединение по строкам (вертикально)
# dim=1 означает объединение по столбцам (горизонтально)

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
concatenated = torch.cat((x, y), dim=0)

print(f"Исходный тензор x:\n{x}")
print(f"Исходный тензор y:\n{y}")

print(f"Результат объединения:\n{concatenated}\n")


Исходный тензор x:
tensor([[1, 2],
        [3, 4]])
Исходный тензор y:
tensor([[5, 6],
        [7, 8]])
Результат объединения:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])



In [5]:
# 2. torch.chunk()
# Функция разделяет тензор на заданное количество частей вдоль указанной размерности
# Если тензор нельзя разделить на равные части, последний чанк будет остаточным

tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor2 = torch.tensor([1, 2, 3, 4, 5, 6, 7])
chunks = torch.chunk(tensor, chunks=3, dim=0)

print(f"Тензор: {tensor}")
print(f"Тензор c остаточным чанком: {tensor2}")
print("Результат разделения на части:")

chunks2 = torch.chunk(tensor2, chunks=3, dim=0)

for i, chunk in enumerate(chunks):
    print(f"Тензор 1, часть {i + 1}: {chunk}")

print()

for i, chunk in enumerate(chunks2):
    print(f"Тензор 2, часть {i + 1}: {chunk}")


Тензор: tensor([1, 2, 3, 4, 5, 6])
Тензор c остаточным чанком: tensor([1, 2, 3, 4, 5, 6, 7])
Результат разделения на части:
Тензор 1, часть 1: tensor([1, 2])
Тензор 1, часть 2: tensor([3, 4])
Тензор 1, часть 3: tensor([5, 6])

Тензор 2, часть 1: tensor([1, 2, 3])
Тензор 2, часть 2: tensor([4, 5, 6])
Тензор 2, часть 3: tensor([7])


In [6]:
# 3. torch.gather()
# Функция gather() собирает значения из тензора по указанным индексам
# Индексы задаются тензором такой же формы, как и результат

src = torch.tensor([[1, 2], [3, 4], [5, 6]])
index = torch.tensor([[0, 1], [1, 0], [0, 0]])
gathered = torch.gather(src, dim=1, index=index)

print(f"Исходный тензор:\n{src}")
print(f"Индексы:\n{index}")
print(f"Результат выборки:\n{gathered}\n")


Исходный тензор:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Индексы:
tensor([[0, 1],
        [1, 0],
        [0, 0]])
Результат выборки:
tensor([[1, 2],
        [4, 3],
        [5, 5]])



In [7]:
# 4. torch.reshape()
# Функция reshape() изменяет форму тензора без изменения его данных
# Новая форма должна сохранять то же количество элементов

original = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
reshaped = torch.reshape(original, (2, 4))

print(f"Исходный тензор: {original}")
print(f"Тензор после изменения формы (2x4):\n{reshaped}\n")


Исходный тензор: tensor([1, 2, 3, 4, 5, 6, 7, 8])
Тензор после изменения формы (2x4):
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])



In [8]:
# 5. torch.squeeze()
# Функция squeeze() удаляет все размерности тензора, равные 1
# Полезно для удаления лишних одномерных размерностей

tensor_with_ones = torch.zeros(1, 2, 1, 3)
squeezed = torch.squeeze(tensor_with_ones)

print(f"Исходная форма: {tensor_with_ones.shape}")
print(f"Форма после сжатия: {squeezed.shape}\n")


Исходная форма: torch.Size([1, 2, 1, 3])
Форма после сжатия: torch.Size([2, 3])



In [9]:
# 6. torch.stack()
# Функция stack() объединяет последовательность тензоров в один тензор вдоль новой размерности
# Все входные тензоры должны иметь одинаковую форму

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])
stacked = torch.stack([tensor1, tensor2, tensor3])

print(f"Тензор 1: {tensor1}")
print(f"Тензор 2: {tensor2}")
print(f"Тензор 3: {tensor3}")
print(f"Результат объединения:\n{stacked}\n")


Тензор 1: tensor([1, 2, 3])
Тензор 2: tensor([4, 5, 6])
Тензор 3: tensor([7, 8, 9])
Результат объединения:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])



In [10]:
# 7. torch.transpose()
# Функция transpose() меняет местами две указанные размерности тензора
# Часто используется для преобразования матриц

matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
transposed = torch.transpose(matrix, 0, 1)

print(f"Исходная матрица:\n{matrix}")
print(f"Транспонированная матрица:\n{transposed}\n")


Исходная матрица:
tensor([[1, 2, 3],
        [4, 5, 6]])
Транспонированная матрица:
tensor([[1, 4],
        [2, 5],
        [3, 6]])



In [11]:
# 8. torch.unsqueeze()
# Функция unsqueeze() добавляет новую размерность размера 1 по указанному индексу
# Полезно при подготовке данных для нейронных сетей

tensor = torch.tensor([1, 2, 3, 4])
unsqueezed = torch.unsqueeze(tensor, dim=0)

print(f"Исходный тензор: {tensor}, форма: {tensor.shape}")
print(f"После добавления размерности: {unsqueezed}, форма: {unsqueezed.shape}\n")


Исходный тензор: tensor([1, 2, 3, 4]), форма: torch.Size([4])
После добавления размерности: tensor([[1, 2, 3, 4]]), форма: torch.Size([1, 4])



In [12]:
# 9. torch.where()
# Функция where() возвращает тензор с элементами из x там, где условие истинно,
# и элементами из y там, где условие ложно

condition = torch.tensor([[True, False], [False, True]])
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
result = torch.where(condition, x, y)

print(f"Условие:\n{condition}")
print(f"Тензор x:\n{x}")
print(f"Тензор y:\n{y}")
print(f"Результат:\n{result}\n")


Условие:
tensor([[ True, False],
        [False,  True]])
Тензор x:
tensor([[1, 2],
        [3, 4]])
Тензор y:
tensor([[5, 6],
        [7, 8]])
Результат:
tensor([[1, 6],
        [7, 4]])



In [13]:
# 10. torch.nonzero()
# Функция nonzero() возвращает индексы всех ненулевых элементов тензора
# Каждая строка в выходном тензоре содержит индексы одного ненулевого элемента

tensor = torch.tensor([[0, 1, 0], [2, 0, 3]])
nonzero_indices = torch.nonzero(tensor)

print(f"Исходный тензор:\n{tensor}")
print(f"Индексы ненулевых элементов:\n{nonzero_indices}")
print("Пояснение: каждая строка содержит [номер_строки, номер_столбца] ненулевого элемента")


Исходный тензор:
tensor([[0, 1, 0],
        [2, 0, 3]])
Индексы ненулевых элементов:
tensor([[0, 1],
        [1, 0],
        [1, 2]])
Пояснение: каждая строка содержит [номер_строки, номер_столбца] ненулевого элемента
